services:
  snipe-mysql:
    image: mysql:5.6
    volumes:
      - snipesql-vol:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    env_file:
      - stack.env
  snipe-it:
    image: snipe/snipe-it
    ports:
      - "${SNIPE_IT_HTTP_PORT}:80"
      - "${SNIPE_IT_HTTPS_PORT}:443"
    volumes:
      - snipeweb-conf:/etc/apache
      - snipeweb-certs:/var/lib/snipeit/ssl
    depends_on:
      - snipe-mysql
    env_file:
      - stack.env
volumes:
  snipesql-vol:
  snipeweb-conf:
  snipeweb-certs:
